apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-db-secret
  namespace: backend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: rds-db-secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: rds!db-2b8beca6-8393-45bc-901d-1ca9de0c8346                             #name of secretmanger in your region not arn 
        property: password
